In [1]:
import pandas as pd

In [14]:
info={
    "name":["Adam","Ave","Devid","jeni","remi"],
    "marks":[54,45,76,67,98]
}


dF=pd.DataFrame(info)
print(dF,type(dF))
print(dF.index)
res=dF.set_index('name')
print(res)
res=dF.reset_index(drop=True)
print(res)
# print(dF.loc['Ave'])

    name  marks
0   Adam     54
1    Ave     45
2  Devid     76
3   jeni     67
4   remi     98 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=5, step=1)
       marks
name
Adam      54
Ave       45
Devid     76
jeni      67
remi      98
    name  marks
0   Adam     54
1    Ave     45
2  Devid     76
3   jeni     67
4   remi     98

In [20]:
dF.head()

    name  marks
0   Adam     54
1    Ave     45
2  Devid     76
3   jeni     67
4   remi     98

dF.tail(2)

In [23]:
dF.tail(2)

   name  marks
3  jeni     67
4  remi     98

In [27]:
res=list(dF.columns)
print(res)

['name', 'marks']

In [34]:
r=sorted(dF.columns)
print(r)

['marks', 'name']

In [36]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [38]:
pd.Series([30,35,40], index=['2015 Sales', '2016 Sales', '2017 Sales'],name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64